config/routes.rb
JobSnapper::Application.routes.draw do
  devise_for  :candidates, :employers,
              :path_names => { :sign_in => "sign-in", :sign_out => "sign-out", :sign_up => "sign-up" }

  namespace :candidates do
    resource :profiles, :except => [:show, :destroy]
  end

  namespace :employers do
    resource :dashboard, :only => [:show], :controller => "dashboard"
  end

  resources :jobs do
    resources :applications, :controller => "jobs/applications", :only => [:index, :show]
  end

  namespace :applicant do
    resource :application, :controller => 'application', only: [:create] do
      member do
        get ":id/accept"    => "application#accept",    :as => "accept"
        get ":id/remove"    => "application#remove",    :as => "remove"
        get ":id/unaccept"  => "application#unaccept",  :as => "unaccept"
      end
    end
  end

  root to: "pages#home"

end

app/models/application.rb
class Application < ActiveRecord::Base
  belongs_to :job
  belongs_to :candidate

  validates_presence_of :job_id
  validates_presence_of :candidate_id

  scope :pending, where("applications.status IS NOT FALSE")

  def pending?
    if status == nil
      return true
    else
      return false
    end
  end

  def accepted?
    if status == true
      return true
    else
      return false
    end
  end

  def rejected?
   if status == false
     return true
   else
     return false
   end
  end
end

app/models/job.rb
class Job < ActiveRecord::Base
  include Addressify
  include Skillable

  belongs_to :employer

  has_many :applications, :dependent => :destroy

  has_one :categorization
  has_one :category, :through => :categorization

  has_one :classification
  has_one :type, :through => :classification

  validates_presence_of :title, :message => "Please include a title"
  validates_presence_of :contact_name, :message => "Please include a contact name"

  validates_presence_of :region, :message => "Please include location"
  validates_presence_of :type, :message => "Please include a job type"
  validates_presence_of :category, :message => "Please include a job category"

  validates_presence_of :summary
  validates_presence_of :description

  self.per_page = 10

  def default_pay_rate_min
    self.pay_rate_min ||= 16
  end

  def default_pay_rate_max
    self.pay_rate_max ||= 21
  end

  def default_start_date
    if start_date
      start_date.strftime('%d %b, %Y')
    else
      start_date = DateTime.now.strftime('%d %b, %Y')
    end
  end

  def formatted_pay_rate_min
    "$#{pay_rate_min}"
  end

  def formatted_pay_rate_max
    "$#{pay_rate_max}"
  end

  def work_type
    "#{type.title}"
  end
end

app/controllers/applicant/application_controller.rb
class Applicant::ApplicationController < ApplicationController
  before_action :authenticate_candidate!, :only => [:create]
  before_action :authenticate_employer!, :only => [:accept, :remove, :unaccept]
  before_action :correct_employer, :only => [:accept, :remove, :unaccept]
  before_action :applyable_candidate, :only => [:create]

  def accept
    @application.status = true

    respond_to do |format|
      if @application.save
        format.html { redirect_to job_applications_path(@application.job.id), notice: "Application successfully accepted." }
        format.json { render json: @application, status: :created, location: @application }
      else
        format.html { render @application }
        format.json { render json: @application.errors, status: :unprocessable_entity }
      end
    end
  end

  def remove
    @application.status = false

    respond_to do |format|
      if @application.save
        format.html { redirect_to job_applications_path(@application.job_id), notice: "Application was removed." }
        format.json { render json: @application, status: :created, location: @application }
      else
        format.html { render @application }
        format.json { render json: @application.errors, status: :unprocessable_entity }
      end
    end
  end

  def unaccept
    @application.status = nil

    respond_to do |format|
      if @application.save
        format.html { redirect_to job_applications_path(@application.job_id), notice: "Application was unaccepted." }
        format.json { render json: @application, status: :created, location: @application }
      else
        format.html { render @application }
        format.json { render json: @application.errors, status: :unprocessable_entity }
      end
    end
  end

  def create
    @application = Application.new(application_params)

    respond_to do |format|
      if @application.save
        format.html { redirect_to @application.job, notice: "Application successfully submitted." }
        format.json { render json: @application, status: :created, location: @application }
      else
        format.html { render @application }
        format.json { render json: @application.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def application_params
    params.require(:application).permit(
      :candidate_id,
      :job_id
      )
  end

  def applyable_candidate
    if current_candidate.profile.nil?
      redirect_to new_candidates_profiles_path, :notice => "You should complete your profile before applying to a job."
    end
  end

  def correct_employer
    @application = Application.find(params[:id])
    job = Job.find(@application.job_id)
    redirect_to root_url unless job.employer_id == current_employer.id
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_filter :authenticate! unless Rails.env == "development" || Rails.env == "test" || Rails.env == "draft"
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :job_search

  def job_search
    @job_search ||= Job.search(params[:q])
  end

  protected

  def authenticate!
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["HTTP_AUTH_USERNAME"] && password == ENV["HTTP_AUTH_PASSWORD"]
    end
  end
end

app/controllers/jobs/applications_controller.rb
class Jobs::ApplicationsController < ActionController::Base
  helper_method :job_search

  def index
    @job = Job.find(params[:job_id])
    render :layout => "application"
  end

  def show
    @job = Job.find(params[:job_id])
    @application = Application.find(params[:id])
    @candidate = Candidate.find(@application.candidate_id)
    @candidate_profile = Candidate::Profile.find(@application.candidate_id)
    render :layout => "application"
  end

  def job_search
    @job_search ||= Job.search(params[:q])
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :authenticate_employer!, :except => [:show, :index]
  before_action :correct_employer, :only => [:edit, :update, :destroy, :applications]
  before_action :build_application, :only => [:show]

  def index
    debugger
    @jobs = job_search.result(:distinct => true).paginate(:page => params[:page])

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @jobs }
    end
  end

  def new
    @job = Job.new
    @categories = Category.all
    @types = Type.all

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @job }
    end
  end

  def create
    @job = current_employer.jobs.build(job_params)

    @job.category = Category.find(params[:job][:category]) unless params[:job][:category].blank?
    @job.type = Type.find(params[:job][:type]) unless params[:job][:type].blank?

    @categories = Category.all
    @types = Type.all

    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: "Job successfully created." }
        format.json { render json: @job, status: :created, location: @job }
      else
        format.html { render new_job_path }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @categories = Category.all
    @types = Type.all
  end

  def show
    @job = Job.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @job }
    end
  end

  def update
    @job.category = Category.find(params[:job][:category])
    @job.type = Type.find(params[:job][:type])

    respond_to do |format|
      if @job.update_attributes(job_params)
        format.html { redirect_to edit_job_path(@job), notice: 'Job was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @job.destroy

    respond_to do |format|
      format.html { redirect_to root_url }
      format.json { head :no_content }
    end
  end

  private

  def build_application
    # An employer cannot apply for jobs, only registered candidates
    # and guests. If we are an employer the application form
    # won't be built. If we are a guest diverge off to build a
    # null set of parameters. If we are a candidate build the
    # appropriate params.
    if current_employer
      return
    elsif current_candidate.nil?
      build_guest_application
    else
      @application = Application.new(candidate_id: current_candidate.id, job_id: params[:id])
      params[:application] = @application
    end
  end

  def build_guest_application
    @application = Application.new(candidate_id: nil, job_id: params[:id])
    params[:application] = @application
  end

  def correct_employer
    @job = current_employer.jobs.find_by(id: params[:id])
    redirect_to root_url if @job.nil?
  end

  def job_params
    params.require(:job).permit(
      :employer_id,
      :title,
      :company,
      :contact_name,
      :contact_number,
      :region_id,
      :city_id,
      :start_date,
      :pay_rate_min,
      :pay_rate_max,
      :summary,
      :description,
      :ideal_candidate,
      :skill_list
      )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def flash_class(level)
    case level
    when :success then "success"
    when :notice then "info"
    when :error then "error"
    when :alert then "warning"
    end
  end

  def application_status_class(application)
    if application.rejected?
      return "error"
    elsif application.pending?
      return ""
    elsif application.accepted?
      return "success"
    end
  end

  def current_user
    if current_candidate
      return current_candidate
    elsif current_employer
      return current_employer
    else
      Guest.new
    end
  end
end

app/views/jobs/applications/index.html.erb
<div class="page-header">
  <h3>Applicants <small>- <%= @job.title %></small></h3>
</div>

<% if @job.applications.length > 0 %>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Name</th>
        <th>Contact number</th>
        <th>Actions</th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @job.applications.pending.order(created_at: :asc).each do |application| %>
        <tr class="<%= application_status_class(application) %>">
          <td><%= application.candidate.profile.name %></td>
          <td><%= application.candidate.profile.contact_number %></td>
          <td><%= link_to "View application", job_application_path(:id => Application.find_by(job_id: params[:job_id], candidate_id: application.candidate.id).id ) %>
          </td>
          <td><%= link_to "Accept", accept_applicant_application_path(application.id) unless application.status == true %></td>
          <% if application.status == true %>
            <td><%= link_to "Unaccept", unaccept_applicant_application_path(application.id), :confirm => "Are you sure you want to unaccept this application?" %></td>
          <% else %>
            <td><%= link_to "Remove", remove_applicant_application_path(application.id), :confirm => "Are you certain you want to remove this application? This cannot be undone." %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <div class="row-fluid">
    <p>This job has no applications yet.</p>
  </div>
<% end %>

app/views/jobs/applications/show.html.erb
<div class="page-header clearfix">
  <h3 class="span11"><%= @candidate_profile.name %> <small>- <%= @job.title %></small></h3>
  <div class="span1 pull-right visible-desktop">
    <span class="thumbnail">
      <%= gravatar_for @candidate %>
    </span>
  </div>
</div>

<div class="row-fluid">
  <%= simple_format(@candidate_profile.about_me) %>

  <h4 class="mtl">Previous work experience</h4>
  <%= simple_format(@candidate_profile.previous_work_experience) %>

  <h4 class="mtl">Applicants details</h4>
  <table class="table table-bordered mbl">
    <tbody>
      <tr>
        <td>Contact number</td>
        <td><%= @candidate_profile.contact_number %></td>
      </tr>
      <tr>
        <td>Location</td>
        <td><%= @candidate_profile.address %></td>
      </tr>
      <% if @candidate_profile.skill_list %>
        <tr>
          <td>Skills</td>
          <td>
            <%= @candidate_profile.skill_list.to_sentence(:last_word_connector => ", ") %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <h4 class="mtl">Next steps</h4>
  <% if @application.status == true %>
    <%= link_to "Unaccept application", unaccept_applicant_application_path(params[:id]), :class => "mbm", :style => "display: block;", :confirm => "Are you sure you want to unaccept this application?" %>
    <%= link_to "Back to view all applications", job_applications_path(params[:job_id]), :class => "mtm", :style => "display: block;" %>
  <% else %>
    <%= link_to "Accept application", accept_applicant_application_path(params[:id]), :class => "btn btn-success btn-embossed" %>
    or
    <%= link_to "Remove application", remove_applicant_application_path(params[:id]), :class => "btn btn-danger btn-embossed" %>
    <br>
    <%= link_to "Back to view all applications", job_applications_path(params[:job_id]), :class => "mtm", :style => "display: block;" %>
  <% end %>
</div>