config/routes.rb
JobSnapper::Application.routes.draw do
  devise_for  :candidates, :employers,
              :path_names => { :sign_in => "sign-in", :sign_out => "sign-out", :sign_up => "sign-up" }

  namespace :candidates do
    resource :profiles, :except => [:show, :destroy]
  end

  namespace :employers do
    resource :dashboard, :only => [:show], :controller => "dashboard"
  end

  resources :jobs do
    resources :applications, :controller => "jobs/applications", :only => [:index, :show]
  end

  namespace :applicant do
    resource :application, :controller => 'application', only: [:create] do
      member do
        get ":id/accept"    => "application#accept",    :as => "accept"
        get ":id/remove"    => "application#remove",    :as => "remove"
        get ":id/unaccept"  => "application#unaccept",  :as => "unaccept"
      end
    end
  end

  root to: "pages#home"

end

app/models/job.rb
class Job < ActiveRecord::Base
  include Addressify
  include Skillable

  belongs_to :employer

  has_many :applications, :dependent => :destroy

  has_one :categorization
  has_one :category, :through => :categorization

  has_one :classification
  has_one :type, :through => :classification

  validates_presence_of :title, :message => "Please include a title"
  validates_presence_of :contact_name, :message => "Please include a contact name"

  validates_presence_of :region, :message => "Please include location"
  validates_presence_of :type, :message => "Please include a job type"
  validates_presence_of :category, :message => "Please include a job category"

  validates_presence_of :summary
  validates_presence_of :description

  self.per_page = 10

  def default_pay_rate_min
    self.pay_rate_min ||= 16
  end

  def default_pay_rate_max
    self.pay_rate_max ||= 21
  end

  def default_start_date
    if start_date
      start_date.strftime('%d %b, %Y')
    else
      start_date = DateTime.now.strftime('%d %b, %Y')
    end
  end

  def formatted_pay_rate_min
    "$#{pay_rate_min}"
  end

  def formatted_pay_rate_max
    "$#{pay_rate_max}"
  end

  def work_type
    "#{type.title}"
  end
end

app/controllers/jobs/applications_controller.rb
class Jobs::ApplicationsController < ActionController::Base
  helper_method :job_search

  def index
    @job = Job.find(params[:job_id])
    render :layout => "application"
  end

  def show
    @job = Job.find(params[:job_id])
    @application = Application.find(params[:id])
    @candidate = Candidate.find(@application.candidate_id)
    @candidate_profile = Candidate::Profile.find(@application.candidate_id)
    render :layout => "application"
  end

  def job_search
    @job_search ||= Job.search(params[:q])
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :authenticate_employer!, :except => [:show, :index]
  before_action :correct_employer, :only => [:edit, :update, :destroy, :applications]
  before_action :build_application, :only => [:show]

  def index
    debugger
    @jobs = job_search.result(:distinct => true).paginate(:page => params[:page])

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @jobs }
    end
  end

  def new
    @job = Job.new
    @categories = Category.all
    @types = Type.all

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @job }
    end
  end

  def create
    @job = current_employer.jobs.build(job_params)

    @job.category = Category.find(params[:job][:category]) unless params[:job][:category].blank?
    @job.type = Type.find(params[:job][:type]) unless params[:job][:type].blank?

    @categories = Category.all
    @types = Type.all

    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: "Job successfully created." }
        format.json { render json: @job, status: :created, location: @job }
      else
        format.html { render new_job_path }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @categories = Category.all
    @types = Type.all
  end

  def show
    @job = Job.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @job }
    end
  end

  def update
    @job.category = Category.find(params[:job][:category])
    @job.type = Type.find(params[:job][:type])

    respond_to do |format|
      if @job.update_attributes(job_params)
        format.html { redirect_to edit_job_path(@job), notice: 'Job was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @job.destroy

    respond_to do |format|
      format.html { redirect_to root_url }
      format.json { head :no_content }
    end
  end

  private

  def build_application
    # An employer cannot apply for jobs, only registered candidates
    # and guests. If we are an employer the application form
    # won't be built. If we are a guest diverge off to build a
    # null set of parameters. If we are a candidate build the
    # appropriate params.
    if current_employer
      return
    elsif current_candidate.nil?
      build_guest_application
    else
      @application = Application.new(candidate_id: current_candidate.id, job_id: params[:id])
      params[:application] = @application
    end
  end

  def build_guest_application
    @application = Application.new(candidate_id: nil, job_id: params[:id])
    params[:application] = @application
  end

  def correct_employer
    @job = current_employer.jobs.find_by(id: params[:id])
    redirect_to root_url if @job.nil?
  end

  def job_params
    params.require(:job).permit(
      :employer_id,
      :title,
      :company,
      :contact_name,
      :contact_number,
      :region_id,
      :city_id,
      :start_date,
      :pay_rate_min,
      :pay_rate_max,
      :summary,
      :description,
      :ideal_candidate,
      :skill_list
      )
  end
end

app/views/jobs/_apply_button.html.erb
<% if disabled %>
  <button class="btn btn-embossed btn-block disabled" name="commit" type="submit" value="" style="margin-top: 50px;">
    You've applied <span class="fui-check"></span>
  </button>
  <% else %>
  <%= form_for(@application, url: applicant_application_path, :html => { :class => "mbn" }) do |f| %>
    <%= f.hidden_field :candidate_id, value: params[:application][:candidate_id] %>
    <%= f.hidden_field :job_id, value: params[:application][:job_id] %>
    <button class="btn btn-info btn-embossed btn-block" name="commit" type="submit" value="Apply now!" style="margin-top: 50px;">
      Apply now <span class="fui-check"></span>
    </button>
  <%  end %>
<% end %>

app/views/jobs/_form.html.erb
<%= form_for(@job, :html => { :class => "form-horizontal" }) do |f| %>
  <legend><%= action %> your job</legend>

  <div class="control-group <%= control_group_error(@job, :title) %>">
    <%= f.label :title, :class => "control-label" %>
    <div class="controls">
      <%= f.text_field :title, :label => "Title" %>
      <%= error_help_text(@job, :title) %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :company, "Company", :class => "control-label" %>
    <div class="controls">
      <%= f.text_field :company %>
    </div>
  </div>

  <div class="control-group <%= control_group_error(@job, :contact_name) %>">
    <%= f.label :contact_name, :class => "control-label" %>
    <div class="controls">
      <%= f.text_field :contact_name %>
      <%= error_help_text(@job, :contact_name) %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :contact_number, :class => "control-label" %>
    <div class="controls">
      <%= f.text_field :contact_number %>
    </div>
  </div>

  <%= render :partial => "shared/form/address", :locals => { :f => f, :obj => @job } %>

  <div class="control-group <%= control_group_error(@job, :type) %>">
    <%= f.label :type, "Job type", :class => "control-label" %>
    <div class="controls">
      <%= collection_select(:job, :type, @types, "id", :title, { :prompt => true }) %>
      <%= error_help_text(@job, :type) %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :start_date, :class => "control-label" %>
    <div class="controls">
      <div class="input-prepend input-datepicker">
        <button type="button" class="btn"><span class="fui-calendar"></span></button>
        <input type="text" class="span2" value="<%= @job.default_start_date %>" id="datepicker-start-date" name="job[start_date]">
      </div>
    </div>
  </div>

  <div class="control-group <%= control_group_error(@job, :category) %>">
    <%= f.label :category, :class => "control-label" %>
    <div class="controls">
      <%= collection_select(:job, :category, @categories, :id, :title, { :prompt => true }) %>
      <%= error_help_text(@job, :category) %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label "Pay range (per hour)", :class => "control-label" %>
    <div class="controls">
      <div id="pay-slider" class="mtm ui-slider ui-slider-horizontal ui-widget ui-widget-content ui-corner-all" aria-disabled="false">
        <div class="ui-slider-segment" style="margin-left: 25%;"></div>
        <div class="ui-slider-segment" style="margin-left: 25%;"></div>
        <div class="ui-slider-segment" style="margin-left: 25%;"></div>
        <span class="ui-slider-value first">$<%= @job.default_pay_rate_min %></span>
        <span class="ui-slider-value last">$<%= @job.default_pay_rate_max %></span>
        <%= f.hidden_field :pay_rate_min, :value => @job.default_pay_rate_min %>
        <%= f.hidden_field :pay_rate_max, :value => @job.default_pay_rate_max %>
      </div>
    </div>
  </div>

  <div class="control-group <%= control_group_error(@job, :summary) %>">
    <%= f.label :summary, :class => "control-label" %>
    <div class="controls">
      <%= f.text_area :summary, :class => "span12", :rows => "3" %>
      <p class="help-block"><small>this will appear on search result pages</small></p>
    </div>
  </div>

  <div class="control-group <%= control_group_error(@job, :description) %>">
    <%= f.label :description, :class => "control-label" %>
    <div class="controls">
      <%= f.text_area :description, :class => "span12", :rows => "12" %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :ideal_candidate, "Your ideal candidate", :class => "control-label" %>
    <div class="controls">
      <%= f.text_area :ideal_candidate, :class => "span12", :rows => "3" %>
    </div>
  </div>

  <%= render :partial => "shared/form/skills", :locals => { :f => f } %>

  <div class="control-group">
    <div class="controls">
      <%= f.submit "#{action}", :class => "btn btn-primary btn-embossed" %>
    </div>
  </div>
<% end %>

app/views/jobs/edit.html.erb
<%= render :partial => "form", :locals => { :action => "Update" } %>

app/views/jobs/index.html.erb
<div class="page-header">
  <h3>Find a job</h3>
</div>
<% @jobs.each do |job| %>
  <div class="media media-job">
    <div class="media-body">
      <h4 class="media-heading"><%= link_to job.title.html_safe, job_path(job) %></h4>
      <div class="mbm">
        <% if job.company %>
          <small><%= job.company %></small><br>
        <% end %>
        <small><%= job.category.title %></small><br>
        <small><%= job.address %></small><br>
        <small><%= job.type.title %></small>
      </div>
      <%= job.summary.html_safe %>
      <p class="mbn mtl"><a href="<%= job_path(job) %>">View this job</small></a></p>
    </div>
  </div>
<% end %>
<%= will_paginate @jobs, :renderer => BootstrapPagination::Rails %>

<% if @jobs.blank? %>
  <h6>Sorry, your search returned no jobs</h6>
<% end %>

app/views/jobs/new.html.erb
<%= render :partial => "form", :locals => { :action => "Create" } %>

app/views/jobs/show.html.erb
<div class="clearfix mbm">
  <h3><%= @job.title %> <small>- <%= @job.category.title %></small></h3>
</div>

<div class="media mbl mtn">
  <div class="media-body">
    <table class="table table-bordered">
      <tbody>
        <tr>
          <td>Pay range (p/h)</td>
          <td><%= @job.formatted_pay_rate_min %> - <%= @job.formatted_pay_rate_max %></td>
        </tr>
        <tr>
          <td>Start date</td>
          <td><%= @job.default_start_date %></td>
        </tr>
        <tr>
          <td>Work type</td>
          <td><%= @job.work_type %></td>
        </tr>
        <tr>
          <td>Location</td>
          <td><%= @job.address %></td>
        </tr>
        <% unless @job.skill_list.empty? %>
          <tr>
            <td>Skills required</td>
            <td>
              <%= @job.skill_list.to_sentence(:last_word_connector => ", ") %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <h6>Job description</h6>
    <%= simple_format(@job.description) %>
    <% unless @job.ideal_candidate.nil? %>
      <div class="well well-job mbn mtl">
        <h6>Ideal candidate</h6>
        <%= simple_format(@job.ideal_candidate) %>
      </div>
    <% end %>
  </div>
</div>

<% if !current_employer %>
  <div class="media mbl mtn">
    <div class="media-body">
      <div class="span9">
        <h6>Does this sound like you?</h6>
        <p>Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor. Sed posuere consectetur est at lobortis.</p>
      </div>
      <div class="span3">
        <% if current_user.can_apply_to(@job) %>
          <%= render :partial => "apply_button", :locals => { :disabled => false } %>
        <% else %>
          <%= render :partial => "apply_button", :locals => { :disabled => true } %>
        <% end %>
      </div>
    </div>
  </div>
<% elsif @job.employer_id == current_employer.id %>
  <div class="row-fluid">
    <%= link_to "View job applications", job_applications_path(@job.id), :class => "btn btn-embossed btn-info btn-block span4 offset4" %>
  </div>
<% end %>