config/routes.rb
JobSnapper::Application.routes.draw do
  devise_for  :candidates, :employers,
              :path_names => { :sign_in => "sign-in", :sign_out => "sign-out", :sign_up => "sign-up" }

  namespace :candidates do
    resource :profiles, :except => [:show, :destroy]
  end

  namespace :employers do
    resource :dashboard, :only => [:show], :controller => "dashboard"
  end

  resources :jobs do
    resources :applications, :controller => "jobs/applications", :only => [:index, :show]
  end

  namespace :applicant do
    resource :application, :controller => 'application', only: [:create] do
      member do
        get ":id/accept"    => "application#accept",    :as => "accept"
        get ":id/remove"    => "application#remove",    :as => "remove"
        get ":id/unaccept"  => "application#unaccept",  :as => "unaccept"
      end
    end
  end

  root to: "pages#home"

end

app/models/employer.rb
class Employer < User
  has_one :user, as: :profile, dependent: :destroy
  has_one :profile, :class_name => "Employer::Profile"
  has_many :jobs, :dependent => :destroy

  def can_apply_to(job)
    false
  end
end

app/controllers/employers/dashboard_controller.rb
class Employers::DashboardController < ApplicationController
  before_action :authenticate_employer!

  def show
    @jobs = Job.where(:employer_id => current_employer.id)
  end
end

app/views/employers/dashboard/show.html.erb
<div class="page-header">
  <h3>My jobs</h3>
</div>

<% if @jobs.any? %>
  <table class="table table-striped">
    <thead>
      <th>Job title</th>
      <th>Actions</th>
      <th></th>
      <th></th>
      <th></th>
    </thead>
    <% @jobs.order(created_at: :asc).each do |job| %>
      <tr>
        <td><%= job.title %></td>
        <td><%= link_to "View", job_path(job.id) %></td>
        <td><%= link_to "Applicants (#{job.applications.count})", job_applications_path(job.id) %></td>
        <td><%= link_to "Edit", edit_job_path(job.id) %></td>
        <td><%= link_to "Close", job_path(job.id) %></td>
      </tr>
    <% end %>
  </table>
<% else %>
  <div class="row-fluid">
    <p>You currently have no jobs.</p>
    <%= link_to "Create a job", new_job_path, :class => "btn btn-info btn-embossed" %>
  </div>
<% end %>