config/routes.rb
JobSnapper::Application.routes.draw do
  devise_for  :candidates, :employers,
              :path_names => { :sign_in => "sign-in", :sign_out => "sign-out", :sign_up => "sign-up" }

  namespace :candidates do
    resource :profiles, :except => [:show, :destroy]
  end

  namespace :employers do
    resource :dashboard, :only => [:show], :controller => "dashboard"
  end

  resources :jobs do
    resources :applications, :controller => "jobs/applications", :only => [:index, :show]
  end

  namespace :applicant do
    resource :application, :controller => 'application', only: [:create] do
      member do
        get ":id/accept"    => "application#accept",    :as => "accept"
        get ":id/remove"    => "application#remove",    :as => "remove"
        get ":id/unaccept"  => "application#unaccept",  :as => "unaccept"
      end
    end
  end

  root to: "pages#home"

end

app/views/shared/navigation/_candidate.html.erb
<li class="<%= 'active' if params[:controller] == 'jobs' %>">
  <%= link_to "Find a job", jobs_path %>
</li>
<% if current_candidate.has_profile? %>
  <li class="<%= 'active' if params[:controller] == 'candidates/profiles' %>">
    <%= link_to "My profile", edit_candidates_profiles_path %>
  </li>
<% else %>
  <li class="<%= 'active' if params[:controller] == 'candidates/profiles' %>">
    <%= link_to "My profile", new_candidates_profiles_path %>
  </li>
<% end %>
<li class="<%= 'active' if params[:controller] == 'devise/registrations' %>">
  <%= link_to "My account", edit_candidate_registration_path %>
</li>
<li><%= link_to "Sign out", destroy_candidate_session_path, :method => :delete  %></li>

app/views/shared/navigation/_employer.html.erb
<li class="<%= 'active' if params[:controller] == 'jobs' && (params[:action] == 'new' || 'edit') %>">
  <%= link_to "List a job", new_job_path  %>
</li>
<li class="<%= 'active' if params[:controller] == 'employers/dashboard' || params[:controller] == 'jobs/applications' %>">
  <%= link_to "My jobs", employers_dashboard_path %>
</li>
<li class="<%= 'active' if params[:controller] == 'devise/registrations' %>">
  <%= link_to "My account", edit_employer_registration_path %>
</li>
<li><%= link_to "Sign out", destroy_employer_session_path, :method => :delete  %></li>

app/views/shared/navigation/_visitor.html.erb
<li><%= link_to "Find a job", jobs_path %></li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown">
    Employers
    <b class="caret"></b>
  </a>
  <ul class="dropdown-menu">
    <li><%= link_to "Sign up", new_employer_registration_path %></li>
    <li><%= link_to "Sign in", new_employer_session_path %></li>
  </ul>
</li>

<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown">
    Job seekers
    <b class="caret"></b>
  </a>
  <ul class="dropdown-menu">
    <li><%= link_to "Sign up", new_candidate_registration_path %></li>
    <li><%= link_to "Sign in", new_candidate_session_path %></li>
  </ul>
</li>